travis:
  secure:
    BINSTAR_TOKEN: sfoCWbYmvJM6IDzgksaSNZoNVMD+y472HeY5JOhQrntqOZwGYerSkf0so1Bow/i6FM1QFe4VGn05Ssc/Ssh6WyhvORxAUp1AEtxgU91RWo16jzI5KZua7vcTSeZjNaH3UmE2R3y8HyATNDFw8ycDMlZsEjnBcGqpls8SMQ3N1IgbdrZYTNuKNxSvcLPKbwWBauagP7Q3zYz43xe/YON57ve5J+EGTEB9sn2J35CsKjbwjc/tj2EfB6+iW10+hWSN8y0NourWGGeHCqLOLQKF1UgJTXQcdlYckujTI8BBDnLxRtHrigLb231pMnGV9WPGJwdYzH33Inz3nFfOSnk02/sMjHkyvRMnV7GODhheugNOQgHvKcua1qgXWl+G2ZVzJPqUKqXKiYXDOwaBZLTecX+m94lb3dO8Rp4os8kJrPCWCj+A8/VK+3QXCFWQOXVA0XcpVrN4pVj+DB8WT23M4yr5D8FjHeraiXFfQoUUdQGZ2a+XPttevvxXeBnuLrRiLXfSngNyihM+bLqgp7asmch5CHSSksu79VmGZFwUJ58gssS46n84fyWR4e9cxJ7UimuL5eihSUksUAXlw7G18hn5BlaJA+Pc/we2wTnPBaSB/+LYK1t9/ymfL/tED84UbVfiKg7MYNT1fZzA6TQST1i9KbCwVLFcEB35y8GKYaA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
